
public enum Type {

    STUDENT_CREDENTIAL_WRITE,
    PROFESSOR_CREDENTIAL_WRITE,
    PROFESSOR_SUBJECT_WRITE,
    STUDENT_VOTE_WRITE,
    PROFESSOR_VOTE_WRITE,
    STUDENT_LAST_ACCESS,
    PROFESSOR_LAST_ACCESS

}